# This Secret is mounted by BinderHub's managed build pods because
# c.KubernetesBuildExecutor.push_secret is configured with this Secret's name.
#
# IMPORTANT: This is _not_ a Kubernetes imagePullSecrets formatted Secret, it
#            instead provides a config file for a docker client.
#
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "binderhub-service.build-pods-docker-config.fullname" . }}
  labels:
    {{- include "binderhub-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  # config.json refers to docker config that should house credentials for the
  # docker client in a build pod to use against the docker-api.
  #
  # Docker's config.json expects something like below, where the xx...xx= string
  # is "<username>:<password>" base64 encoded.
  #
  # {
  #   "auths": {
  #     "https://index.docker.io/v1/": {
  #       "auth": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
  #     }
  #   }
  # }
  #
  # ref: https://github.com/jupyterhub/binderhub/blob/79c5f61a992010f108637e3c434d9e606a3c8f72/binderhub/build.py#L397-L406
  #
  {{- /* initialize a dict to represent a docker client config */}}
  {{- $dockerConfig := dict }}

  {{- $server := .Values.buildPodsRegistryCredentials.server }}
  {{- $username := .Values.buildPodsRegistryCredentials.username }}
  {{- $password := .Values.buildPodsRegistryCredentials.password }}
  {{- $blob := printf "%s:%s" $username $password | b64enc }}
  {{- $credentials := dict "auths" (dict $server (dict "auth" $blob)) }}

  {{- /* merge docker client config with registry credentials */}}
  {{- if .Values.config.BinderHub.use_registry }}
  {{- $dockerConfig = merge $dockerConfig $credentials }}
  {{- end }}

  {{- /* merge docker client config of any kind */}}
  {{- if .Values.buildPodsDockerConfig }}
  {{- $dockerConfig = merge $dockerConfig .Values.buildPodsDockerConfig }}
  {{- end }}
  config.json: |
    {{- $dockerConfig | toPrettyJson | nindent 4 }}
