kind: Secret
apiVersion: v1
metadata:
  name: binder-secret
type: Opaque
data:
  {{- $values :=  dict "config" dict }}
  {{- $cfg := .Values.config }}
  binder.hub-token: {{ .Values.jupyterhub.hub.services.binder.apiToken | b64enc | quote }}
  {{- /* every 'pick' here should be matched with a corresponding 'omit' in secret.yaml */ -}}
  {{- if $cfg.GitHubRepoProvider }}
  {{- $_ := set $values.config "GitHubRepoProvider" (pick $cfg.GitHubRepoProvider "client_id" "client_secret" "access_token") }}
  {{- end }}
  {{- if $cfg.GitLabRepoProvider }}
  {{- $_ := set $values.config "GitLabRepoProvider" (pick $cfg.GitLabRepoProvider "access_token" "private_token") }}
  {{- end }}
  values.yaml: {{ $values | toYaml | b64enc | quote }}
---
{{- if .Values.config.BinderHub.use_registry }}
kind: Secret
apiVersion: v1
metadata:
  name: binder-push-secret
type: Opaque
data:
  config.json: {{ include "registryDockerConfig" . | b64enc | quote }}
{{- end }}
