kind: Secret
apiVersion: v1
metadata:
  name: binder-secret
type: Opaque
data:
  {{ if .Values.registry.enabled -}}
  config.json: {{ template "imagePullSecret" . }}
  {{- end }}
  binder.hub-token: {{ .Values.jupyterhub.hub.services.binder.apiToken | b64enc | quote }}
  {{ if .Values.github.clientId -}}
  github.client-id: {{ .Values.github.clientId | b64enc | quote }}
  {{- end }}
  {{ if .Values.github.clientSecret -}}
  github.client-secret: {{ .Values.github.clientSecret | b64enc | quote }}
  {{- end }}
  {{ if .Values.github.accessToken -}}
  github.access-token: {{ .Values.github.accessToken | b64enc | quote }}
  {{- end }}
  {{ if .Values.gitlab.accessToken -}}
  gitlab.access-token: {{ .Values.gitlab.accessToken | b64enc | quote }}
  {{- end }}
  {{ if .Values.gitlab.privateToken -}}
  gitlab.private-token: {{ .Values.gitlab.privateToken | b64enc | quote }}
  {{- end }}
