{{- /*
  Note that changes to the rendered version of this
  file will trigger a restart of the BinderHub pod
  through a annotation containing a hash of this
  file rendered.
*/ -}}
kind: Secret
apiVersion: v1
metadata:
  name: binder-secret
type: Opaque
stringData:
  {{- /*
    Stash away relevant Helm template values for
    the BinderHub Python application to read from
    in binderhub_config.py.
  */}}
  values.yaml: |
    {{- pick .Values "config" "cors" "dind" "extraConfig" | toYaml | nindent 4 }}

  {{- /* Glob files to allow them to be mounted by the binderhub pod */}}
  {{- /* key=filename: value=content */}}
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}

  {{- with include "jupyterhub.extraFiles.stringData" .Values.extraFiles }}
  {{- . | nindent 2 }}
  {{- end }}

{{- with include "jupyterhub.extraFiles.data" .Values.extraFiles }}
data:
  {{- . | nindent 2 }}
{{- end }}
---
{{- if or .Values.config.BinderHub.use_registry .Values.config.BinderHub.buildDockerConfig }}
kind: Secret
apiVersion: v1
metadata:
  name: binder-build-docker-config
type: Opaque
data:
  config.json: {{ include "buildDockerConfig" . | b64enc | quote }}
{{- end }}
