{{ if .Values.dind.enabled -}}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-dind
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name:  {{ .Release.Name }}-dind
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-dind
        app: binder
        component: dind
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      nodeSelector: {{ (default (dict) .Values.config.BinderHub.build_node_selector) | toJson  }}
      {{ if .Values.dind.initContainers -}}
      initContainers:
{{ toYaml .Values.dind.initContainers | indent 10 }}
      {{- end }}
      {{- if .Values.jupyterhub.scheduling.podPriority.enabled }}
      priorityClassName: {{ .Release.Name }}-default-priority
      {{- end }}
      containers:
      - name: dind
        image: {{ .Values.dind.daemonset.image.name }}:{{ .Values.dind.daemonset.image.tag }}
        resources:
{{ toYaml .Values.dind.resources | indent 10}}
        args:
          - dockerd
          - --storage-driver={{ .Values.dind.storageDriver }}
          - -H unix://{{ .Values.dind.hostSocketDir }}/docker.sock
        securityContext:
          privileged: true
        volumeMounts:
        - name: dockerlib-dind
          mountPath: /var/lib/docker
        - name: rundind
          mountPath: {{ .Values.dind.hostSocketDir }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dockerlib-dind
        hostPath:
          path: {{ .Values.dind.hostLibDir }}
          type: DirectoryOrCreate
      - name: rundind
        hostPath:
          path: {{ .Values.dind.hostSocketDir }}
          type: DirectoryOrCreate
{{- end }}
