{{- if .Values.dind.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-dind
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name:  {{ .Release.Name }}-dind
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-dind
        app: binder
        component: dind
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      tolerations:
      - effect: NoSchedule
        key: hub.jupyter.org/dedicated
        operator: Equal
        value: user
      - effect: NoSchedule
        key: hub.jupyter.org_dedicated
        operator: Equal
        value: user
      nodeSelector: {{ .Values.config.BinderHub.build_node_selector | default dict | toJson }}
      {{- with .Values.dind.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: dind
        image: {{ .Values.dind.daemonset.image.name }}:{{ .Values.dind.daemonset.image.tag }}
        resources:
          {{- .Values.dind.resources | toYaml | nindent 10 }}
        args:
          - dockerd
          - --storage-driver={{ .Values.dind.storageDriver }}
          - -H unix://{{ .Values.dind.hostSocketDir }}/docker.sock
          {{- with .Values.dind.daemonset.extraArgs }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: dockerlib-dind
          mountPath: /var/lib/docker
        - name: rundind
          mountPath: {{ .Values.dind.hostSocketDir }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dockerlib-dind
        hostPath:
          path: {{ .Values.dind.hostLibDir }}
          type: DirectoryOrCreate
      - name: rundind
        hostPath:
          path: {{ .Values.dind.hostSocketDir }}
          type: DirectoryOrCreate
{{- end }}
