{{- /*
  Changes to this rendered manifest triggers a restart of the binderhub-service
  pod as the pod specification includes an annotation with a checksum of this.
*/ -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "binderhub-service.binderhub.fullname" . }}
  labels:
    {{- include "binderhub-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- /*
    To restart the binderhub-service pod only when relevant, we pick out the
    chart configuration actually consumed in the mounted binderhub_config.py
    file.
  */}}
  chart-config.yaml: |
    {{- pick .Values "config" "extraConfig" | toYaml | nindent 4 }}

  {{- with .Values.extraCredentials.googleServiceAccountKey }}
  gcp-sa-key.json: |
    {{- . | nindent 4 }}
  {{- end }}

  {{- /* Glob files to allow them to be mounted by the binderhub pod */}}
  {{- /* key=filename: value=content */}}
  {{- (.Files.Glob "mounted-files/*").AsConfig | nindent 2 }}
