#!/bin/bash
# This script publishes the Helm chart to the JupyterHub Helm chart repo and
# pushes associated built docker images to Docker hub using chartpress.
# --------------------------------------------------------------------------

# Exit on error and raise an error for unset environment variables
set -eu

# Decrypt a private SSH key having its public key registered on GitHub. It will
# be used to establish an identity with rights to push to the git repository
# hosting our Helm charts: https://github.com/jupyterhub/helm-chart
openssl aes-256-cbc -K $encrypted_d8355cc3d845_key -iv $encrypted_d8355cc3d845_iv -in ci/publish-id_rsa.enc -out ci/id_rsa -d
chmod 0400 ci/id_rsa

# Configure docker with credentials to let chartpress push images to docker hub.
docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

# Activate logging of bash commands now that the sensitive stuff is done
set -x

cd helm-chart

# As chartpress uses git to push to our Helm chart repository, we configure
# git ahead of time to use the identity we decrypted earlier.
export GIT_SSH_COMMAND="ssh -i ${PWD}/ci/id_rsa"

if [ "${TRAVIS_TAG:-}" == "" ]; then
    # Using --long, we are ensured to get a build suffix, which ensures we don't
    # build the same tag twice. Using --extra-message, we help automation like
    # henchbot to submit update PRs to jupyterhub/mybinder.org-deploy.
    #
    # ref: https://github.com/jupyterhub/chartpress#usage
    # ref: https://github.com/henchbot/mybinder.org-upgrades
    LATEST_COMMIT_TITLE=$(git log -1 --pretty=%B | head -n1 | sed 's/^.*\(#[0-9]*\).*/\1/')
    chartpress --push --publish-chart --long --extra-message "${TRAVIS_REPO_SLUG}${LATEST_COMMIT_TITLE}"
else
    # Setting a tag explicitly enforces a rebuild if this tag had already been
    # built and we wanted to override it.
    chartpress --push --publish-chart --tag "${TRAVIS_TAG}"
fi

# Let us log the changes chartpress did, it should include replacements for
# fields in values.yaml, such as what tag for various images we are using.
git --no-pager diff
