#!/bin/bash

set -ex
./testing/minikube/install-hub --auth
# DEBUG: give the hub a chance to wake up
sleep 10
export ASYNC_TEST_TIMEOUT=15
pytest -vsx --cov binderhub/tests/test_auth.py
helm delete --purge binder-test-hub
